services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\FrameworkBundle\Command\:
        resource: '../../Command'

    Shopsys\FrameworkBundle\Command\ServerRunWithCustomRouterCommand:
        arguments:
            - '%kernel.project_dir%/web'
            - '%kernel.environment%'

    Shopsys\FrameworkBundle\Command\ServerStartWithCustomRouterCommand:
        arguments:
            - '%kernel.project_dir%/web'
            - '%kernel.environment%'

    Shopsys\FrameworkBundle\Command\CreateApplicationDirectoriesCommand:
        arguments:
            - '%kernel.project_dir%'

    Shopsys\FrameworkBundle\Command\GenerateGruntfileCommand:
        arguments:
            - '%shopsys.resources_dir%'
            - '%shopsys.framework.resources_dir%'
            - '%shopsys.root_dir%'

    Shopsys\FrameworkBundle\Command\ImageDemoCommand:
        arguments:
            - '%shopsys.data_fixtures_images.resources_dir%'
            - '%shopsys.data_fixtures_images_sql%'
            - '%shopsys.image_dir%'
            - '%shopsys.domain_images_dir%'

    Shopsys\MigrationBundle\Command\GenerateMigrationCommand:
        arguments:
            - '%shopsys.vendor_dir%'
