services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\FrameworkBundle\Component\Form\TimedFormTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Shopsys\FrameworkBundle\Form\:
        resource: '../../Form/'

    Shopsys\FrameworkBundle\Form\CollectionTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }

    Shopsys\FrameworkBundle\Form\EmptyMessageChoiceTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

    Shopsys\FrameworkBundle\Form\FormRenderingConfigurationExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Shopsys\FrameworkBundle\Form\InvertChoiceTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

    Shopsys\FrameworkBundle\Form\MoneyTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\MoneyType }

    Shopsys\FrameworkBundle\Form\WysiwygTypeExtension:
        arguments:
            $entrypointsPath: '%shopsys.json_entrypoints_path%'
        tags:
            - { name: form.type_extension, extended_type: FOS\CKEditorBundle\Form\Type\CKEditorType }
