language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - ~/.composer/cache

before_install:
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install

script:
  - php vendor/bin/parallel-lint ./src
  - php vendor/bin/ecs check --config=vendor/shopsys/coding-standards/easy-coding-standard.yml --verbose ./src ./tests
  - php vendor/bin/phpstan analyze -c ./phpstan.neon ./src --level=0
  - php vendor/bin/phpunit
