parameters:
    shopsys.framework.resources_dir: "%shopsys.framework.root_dir%/src/Resources"
    shopsys.router.domain.cache_dir: "%kernel.cache_dir%/routing/base"
    shopsys.router.localized.cache_dir: "%kernel.cache_dir%/routing/localized"
