
front_error_page:
    defaults:
        _controller: Shopsys\FrameworkBundle\Component\Error\ErrorController::errorPagePreviewAction
    path: /_error/{code}/
    requirements:
        code: \d+

front_error_page_format:
    defaults:
        _controller: Shopsys\FrameworkBundle\Component\Error\ErrorController::errorPagePreviewAction
    path: /_error/{code}/{_format}/
    requirements:
        _format: css|html|js|json|txt|xml
        code: \d+
shopsys_framework_admin:
    prefix: /admin
    resource: "@ShopsysFrameworkBundle/Controller"
    type: annotation
