imports:
    - { resource: packages_registry.yaml }

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\FrameworkBundle\Command\ExtendedClassesAnnotationsCommand:
        arguments:
            - '%kernel.project_dir%'

    Shopsys\FrameworkBundle\Component\ClassExtension\ClassExtensionRegistry:
        arguments:
            $entityExtensionMap: '%shopsys.entity_extension.map%'
            $packagesRegistry: '%shopsys.packages.registry%'

    Shopsys\FrameworkBundle\Component\Elasticsearch\Debug\ElasticsearchCollector:
        tags:
            - { name: 'data_collector', template: '@ShopsysFramework/Debug/Elasticsearch/template.html.twig', id: 'shopsys.elasticsearch_collector' }

    Shopsys\FrameworkBundle\Component\Elasticsearch\Debug\ElasticsearchRequestCollection:

    shopsys.component.elasticsearch.tracer:
        class: Shopsys\FrameworkBundle\Component\Elasticsearch\Debug\ElasticsearchTracer
