services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Shopsys\FrameworkBundle\Model\Feed\FeedRegistry:
        arguments:
            $knownTypes: ['daily', 'hourly']
            $defaultType: 'daily'

    Shopsys\FrameworkBundle\Component\Domain\Domain:
        factory: ['@Shopsys\FrameworkBundle\Component\Domain\DomainFactory', create]
        arguments:
            - '%shopsys.domain_config_filepath%'
            - '%shopsys.domain_urls_config_filepath%'

    Shopsys\FrameworkBundle\Model\Product\ProductOnCurrentDomainFacade: ~

    prezent_doctrine_translatable.listener:
        class: Tests\FrameworkBundle\Test\TestTranslatableListener
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            $factory: '@prezent_doctrine_translatable.metadata_factory'
            $domain: '@Shopsys\FrameworkBundle\Component\Domain\Domain'
            $administrationFacade: '@Shopsys\FrameworkBundle\Model\Administration\AdministrationFacade'
            $adminLocale: '%shopsys.admin_locale%'

    Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportSubscriber:
        autoconfigure: false

    Shopsys\FrameworkBundle\Component\Elasticsearch\IndexDefinitionLoader:
        arguments:
            $indexDefinitionsDirectory: '%shopsys.elasticsearch.structure_dir%'
            $indexPrefix: 'test_%env(ELASTIC_SEARCH_INDEX_PREFIX)%'
